### **Telco Customer Churn Prediction - Class Imbalance**

**Objective:** To develop a machine learning classification model that predicts customers who are likely to discontinue their telecom subscription services. The project aims to identify the key factors influencing customer churn through data cleaning, feature engineering, model training, and evaluation, enabling telecom companies to implement targeted customer retention strategies and reduce revenue loss.

**Guiding Principles for this Notebook:** 

+ Import Libraries
+ Load Data
+ Check Target Distributions
+ Define the Functions
+ Apply the functions

**Import Libraries**

In [1]:
import pandas as pd
import numpy as np
from imblearn.over_sampling import SMOTE

**Load Data**

In [6]:
data = pd.read_parquet("C:\\Users\\KOLADE\\OneDrive\\Documents\\AkoladeDSJourney\\Telco-Customer-Churn-Prediction\\data\\processed\\train_processed.parquet")
train_df = data.copy()

train_df.head()

,num__tenure,num__MonthlyCharges,cat__SeniorCitizen_Yes,cat__Partner_Yes,cat__Dependents_Yes,cat__InternetService_Fiber optic,cat__InternetService_No,cat__OnlineSecurity_Yes,cat__OnlineBackup_Yes,cat__DeviceProtection_Yes,cat__TechSupport_Yes,cat__StreamingTV_Yes,cat__StreamingMovies_Yes,cat__Contract_One year,cat__Contract_Two year,cat__PaperlessBilling_Yes,cat__PaymentMethod_Credit card (automatic),cat__PaymentMethod_Electronic check,cat__PaymentMethod_Mailed check,Churn
0,0.881078,0.195927,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0
1,-1.284263,0.522755,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0
2,-0.793997,-1.509551,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0
3,-0.344587,1.053643,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0
4,-1.079985,0.308740,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0

In [8]:
# separate features and target variable
X_train = train_df.drop('Churn', axis=1)
y_train = train_df['Churn']

print(f"X_train shape: {X_train.shape}, y_train shape: {y_train.shape}")
# check the class distribution
print("\nClass distribution before SMOTE:")
print(y_train.value_counts())

X_train shape: (4930, 19), y_train shape: (4930,)

Class distribution before SMOTE:
Churn
0    3635
1    1295
Name: count, dtype: int64

**Define the Functions**

In [24]:
# Check the class distribution before applying SMOTE
def check_class_distribution(y):
    class_counts = y.value_counts()
    percentages = (class_counts / len(y)) * 100
    summary = pd.DataFrame({
        'Class': class_counts.index.map({0: 'No Churn', 1: 'Churn'}),
        'Count': class_counts.values,
        'Percentage': [f"{np.round(p, 2)}%" for p in percentages.values]
    })
    return summary

In [10]:
# apply SMOTE to balance the classes
def apply_smote(X, y, random_state=42):
    smote = SMOTE(random_state=random_state)
    x_smote, y_smote = smote.fit_resample(X, y)
    return x_smote, y_smote

In [11]:
# save the balanced dataset to parquet files
def save_smote_data(X, y, filepath):
    balanced_df = pd.DataFrame(X, columns=X.columns)
    balanced_df['Churn'] = y
    balanced_df.to_parquet(filepath, index=False)
    print(f"Balanced dataset saved to {filepath}")
    return balanced_df

**Apply the Functions**

In [25]:
# check the class distribution before applying SMOTE
print("\nClass distribution before SMOTE:")
check_class_distribution(y_train)

Class distribution before SMOTE:

      Class  Count Percentage
0  No Churn   3635     73.73%
1     Churn   1295     26.27%

In [26]:
# apply SMOTE to balance the classes
X_train_smote, y_train_smote = apply_smote(X_train, y_train)

# check the class distribution after applying SMOTE
print("\nClass distribution after SMOTE:")
check_class_distribution(y_train_smote)

Class distribution after SMOTE:

      Class  Count Percentage
0  No Churn   3635      50.0%
1     Churn   3635      50.0%

In [27]:
# save the balanced dataset to parquet files
filepath = "C:\\Users\\KOLADE\\OneDrive\\Documents\\AkoladeDSJourney\\Telco-Customer-Churn-Prediction\\data\\processed\\train_smote.parquet"
save_smote_data(X_train_smote, y_train_smote, filepath)

Balanced dataset saved to C:\Users\KOLADE\OneDrive\Documents\AkoladeDSJourney\Telco-Customer-Churn-Prediction\data\processed\train_smote.parquet

,num__tenure,num__MonthlyCharges,cat__SeniorCitizen_Yes,cat__Partner_Yes,cat__Dependents_Yes,cat__InternetService_Fiber optic,cat__InternetService_No,cat__OnlineSecurity_Yes,cat__OnlineBackup_Yes,cat__DeviceProtection_Yes,cat__TechSupport_Yes,cat__StreamingTV_Yes,cat__StreamingMovies_Yes,cat__Contract_One year,cat__Contract_Two year,cat__PaperlessBilling_Yes,cat__PaymentMethod_Credit card (automatic),cat__PaymentMethod_Electronic check,cat__PaymentMethod_Mailed check,Churn
0,0.881078,0.195927,0.0,1.0,1.000000,0.000000,0.0,0.000000,1.000000,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0
1,-1.284263,0.522755,0.0,0.0,0.000000,1.000000,0.0,0.000000,0.000000,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0
2,-0.793997,-1.509551,0.0,0.0,0.000000,0.000000,1.0,0.000000,0.000000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0
3,-0.344587,1.053643,1.0,1.0,1.000000,1.000000,0.0,0.000000,0.000000,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0
4,-1.079985,0.308740,1.0,0.0,0.000000,1.000000,0.0,1.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7265,-0.797892,-1.334092,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1
7266,-1.257549,0.365126,0.0,0.0,0.217949,1.000000,0.0,0.000000,0.217949,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
7267,-0.761327,0.119449,0.0,0.0,0.000000,0.240071,0.0,0.759929,0.000000,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1
7268,-1.284263,0.181458,0.0,0.0,0.000000,1.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1
7269,-0.184540,0.866872,0.0,0.0,0.000000,1.000000,0.0,0.000000,0.000000,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1

**Next:** Telco Customer Churn Prediction - Modeling
> **notebook:** *`07_modeling.ipynb`*
>
> **src:** *`modeling.py`*, *`evaluation.py`*