### **Telco Customer Churn Prediction - Modeling**

**Objective:** To develop a machine learning classification model that predicts customers who are likely to discontinue their telecom subscription services. The project aims to identify the key factors influencing customer churn through data cleaning, feature engineering, model training, and evaluation, enabling telecom companies to implement targeted customer retention strategies and reduce revenue loss.

**Guiding Principles for this Notebook:** 

+ Import Libraries
+ Load Data
+ Train Original train dataset
+ Train train dataset with class weights
+ Train the SMOTE train dataset
+ Save results as csv

**Import Libraries**

In [1]:
import pandas as pd

from src.modeling import get_models
from src.evaluation import evaluate_models

**Load Data**

In [2]:
# import the processed train and test datasets
train_data = pd.read_parquet("C:\\Users\\KOLADE\\OneDrive\\Documents\\AkoladeDSJourney\\Telco-Customer-Churn-Prediction\\data\\processed\\train_processed.parquet")
train_df = train_data.copy()
test_data = pd.read_parquet("C:\\Users\\KOLADE\\OneDrive\\Documents\\AkoladeDSJourney\\Telco-Customer-Churn-Prediction\\data\\processed\\test_processed.parquet")
test_df = test_data.copy()

# import the balanced train dataset after applying SMOTE
smote_train_data = pd.read_parquet("C:\\Users\\KOLADE\\OneDrive\\Documents\\AkoladeDSJourney\\Telco-Customer-Churn-Prediction\\data\\processed\\train_smote.parquet")
smote_train_df = smote_train_data.copy()

print(f"Train dataset shape: {train_df.shape}")
print(f"SMOTE balanced train dataset shape: {smote_train_df.shape}")
print(f"Test dataset shape: {test_df.shape}")

Train dataset shape: (4930, 20)
SMOTE balanced train dataset shape: (7270, 20)
Test dataset shape: (2113, 20)

**Split Data**

In [3]:
# Split the original train dataset into features and target variable
X_train = train_df.drop(columns=['Churn'])
y_train = train_df['Churn']

# Split the test dataset into features and target variable
X_test = test_df.drop(columns=['Churn'])
y_test = test_df['Churn']

# Split the SMOTE balanced train dataset into features and target variable
X_train_smote = smote_train_df.drop(columns=['Churn'])
y_train_smote = smote_train_df['Churn']

**Build models with original train dataset**

In [4]:
models = get_models(y_train = y_train)
print(f"Models to be evaluated: {list(models.keys())}")

Models to be evaluated: ['Logistic Regression', 'Decision Tree', 'Random Forest', 'XGBoost']

In [5]:
# evaluate the models on the original train dataset
original_results = evaluate_models(
    models, 
    X_train, 
    y_train, 
    X_test, 
    y_test, 
    experiment_name="original_train"
)

original_results

,Experiment,Model,Accuracy,Precision,Recall,F1,ROC_AUC
0,original_train,Logistic Regression,0.8074,0.6765,0.5575,0.6113,0.8557
1,original_train,Decision Tree,0.7298,0.5027,0.4808,0.4915,0.6520
2,original_train,Random Forest,0.7974,0.6698,0.5017,0.5737,0.8278
3,original_train,XGBoost,0.7937,0.6500,0.5209,0.5783,0.8321

**Build models with original train datasets + class weight**

In [6]:
cw_models = get_models(
    y_train = y_train, 
    use_class_weights = True
)

print(f"Models with class weights to be evaluated:\n {list(cw_models.keys())}")

Models with class weights to be evaluated:
 ['Logistic Regression', 'Decision Tree', 'Random Forest', 'XGBoost']

In [7]:
# evaluate the models on the original + class weights train dataset
cw_results = evaluate_models(
    cw_models, 
    X_train, 
    y_train, 
    X_test, 
    y_test, 
    experiment_name="original + class weights"
)

cw_results

,Experiment,Model,Accuracy,Precision,Recall,F1,ROC_AUC
0,original + class weights,Logistic Regression,0.7539,0.5301,0.8293,0.6467,0.8550
1,original + class weights,Decision Tree,0.7345,0.5123,0.4704,0.4905,0.6523
2,original + class weights,Random Forest,0.7885,0.6523,0.4739,0.5489,0.8235
3,original + class weights,XGBoost,0.7728,0.5666,0.6969,0.6250,0.8330

**Build models with the SMOTE train datasets**

In [8]:
smote_models = get_models(
    y_train = y_train_smote
)
print(f"Models with SMOTE to be evaluated:\n {list(smote_models.keys())}")

Models with SMOTE to be evaluated:
 ['Logistic Regression', 'Decision Tree', 'Random Forest', 'XGBoost']

In [9]:
# evaluate the models on the SMOTE balanced train dataset
smote_results = evaluate_models(
    smote_models, 
    X_train_smote, 
    y_train_smote, 
    X_test, 
    y_test, 
    experiment_name="SMOTE"
)

smote_results

,Experiment,Model,Accuracy,Precision,Recall,F1,ROC_AUC
0,SMOTE,Logistic Regression,0.7525,0.5288,0.8153,0.6415,0.8541
1,SMOTE,Decision Tree,0.7227,0.4905,0.5418,0.5149,0.6647
2,SMOTE,Random Forest,0.7761,0.5933,0.5592,0.5758,0.8225
3,SMOTE,XGBoost,0.7866,0.6059,0.6132,0.6095,0.8303

**Save results**

In [11]:
# save the results to CSV files
original_results.to_csv("C:\\Users\\KOLADE\\OneDrive\\Documents\\AkoladeDSJourney\\Telco-Customer-Churn-Prediction\\reports\\results\\original_results.csv", index=False)
print(r"Original results saved to ..reports\\results as CSV.")

cw_results.to_csv("C:\\Users\\KOLADE\\OneDrive\\Documents\\AkoladeDSJourney\\Telco-Customer-Churn-Prediction\\reports\\results\\cw_results.csv", index=False)
print(r"Class weights results saved to ..reports\\results as CSV.")

smote_results.to_csv("C:\\Users\\KOLADE\\OneDrive\\Documents\\AkoladeDSJourney\\Telco-Customer-Churn-Prediction\\reports\\results\\smote_results.csv", index=False)
print(r"SMOTE results saved to ..reports\\results as CSV.")

Original results saved to ..reports\\results as CSV.
Class weights results saved to ..reports\\results as CSV.
SMOTE results saved to ..reports\\results as CSV.

**Next:** Telco Customer Churn Prediction - Model Comparison
> **notebook:** *`08_model_comarison.ipynb`*