## Exploraory Data Analysis

### Import Libraries & connect to postgresql

In [1]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:250899@localhost:5432/Olist_Brazilian')

#### Pull data from postgresql

In [2]:
## pull data from sql view
dim_date = pd.read_sql('SELECT * FROM dim_date', con=engine)
dim_customer = pd.read_sql('SELECT * FROM dim_customer', con=engine)
dim_product = pd.read_sql('SELECT * FROM dim_product', con=engine)
fact_orders = pd.read_sql('SELECT * FROM fact_orders', con=engine)
fact_payments = pd.read_sql('SELECT * FROM fact_payments', con=engine)
fact_order_items = pd.read_sql('SELECT * FROM fact_order_items', con=engine)

print("Data pulled from SQL views successfully.")

Data pulled from SQL views successfully.

### Data Checks

#### Dim_Date

In [3]:
print(f"shape of dim_date: {dim_date.shape}")
print(f"missing values in dim_date: {dim_date.isnull().sum().sum()}")
print(f"duplicate values in dim_date: {dim_date.duplicated().sum()}")

dim_date.head()

shape of dim_date: (800, 10)
missing values in dim_date: 0
duplicate values in dim_date: 0

,date_key,year,quarter,month,month_name,year_month,week_of_year,day_of_month,day_name,is_weekend
0,2016-09-04,2016,3,9,September,2016-09,35,4,Sunday,True
1,2016-09-05,2016,3,9,September,2016-09,36,5,Monday,False
2,2016-09-06,2016,3,9,September,2016-09,36,6,Tuesday,False
3,2016-09-07,2016,3,9,September,2016-09,36,7,Wednesday,False
4,2016-09-08,2016,3,9,September,2016-09,36,8,Thursday,False

#### Dim_Customer

In [4]:
print(f"shape of dim_customer: {dim_customer.shape}")
print(f"missing values in dim_customer: {dim_customer.isnull().sum().sum()}")
print(f"duplicate values in dim_customer: {dim_customer.duplicated().sum()}")

dim_customer.head()

shape of dim_customer: (99441, 5)
missing values in dim_customer: 0
duplicate values in dim_customer: 0

,customer_id,customer_unique_id,customer_city,customer_state,customer_zip_code_prefix
0,d387341bbce5ab96e3647bb0e8d0b55a,91e6fd64694fa9a828270d442ba88e03,embu,SP,06835
1,f7b083bc0eefdf761a28318a9052cf4a,73a0200d198dbc7022fbcb361cbef7f9,ibia,MG,38950
2,366c88e3ee5ed365c8529a9639c8b91c,8797820f6554668a5b835ff74cd077df,bage,RS,96400
3,915859a34b24020b5b9fd32c8ac40f0d,2852756794b74680d1de8e8e8b8421ff,belem,PA,66045
4,f343704e8d64e463a7147138a8d21b6b,16a909e83380bb2ae4676ca69ac30886,bage,RS,96418

#### Dim_Product

In [5]:
print(f"shape of dim_product: {dim_product.shape}")
print(f"missing values in dim_product: {dim_product.isnull().sum().sum()}")
print(f"duplicate values in dim_product: {dim_product.duplicated().sum()}")

dim_product.head()

shape of dim_product: (32951, 3)
missing values in dim_product: 0
duplicate values in dim_product: 0

                         product_id product_category  is_uncategorized
0  1e9e8ef04dbcff4541ed26657ea517e5        perfumery             False
1  3aa071139cb16b67ca9e5dea641aaa2f              art             False
2  96bd76ec8810374ed1b65e291975717f   sports_leisure             False
3  cef67bcfe19066a932b7673e239eb23d             baby             False
4  9dc1a7de274444849c219cff195d0b71       housewares             False

#### Fact_Orders

In [6]:
print(f"shape of fact_orders: {fact_orders.shape}")
print(f"missing values in fact_orders: {fact_orders.isnull().sum().sum()}")
print(f"duplicate values in fact_orders: {fact_orders.duplicated().sum()}")

fact_orders.head()

shape of fact_orders: (99441, 14)
missing values in fact_orders: 13626
duplicate values in fact_orders: 0

,order_id,customer_id,order_purchase_date,order_status,is_delivered,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,total_payment_value,is_valid_delivery_sequence,delivery_days,is_on_time_delivery
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,2017-10-02,delivered,True,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,38.71,True,8.0,True
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,2018-07-24,delivered,True,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,141.46,True,14.0,True
2,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,2017-11-18,delivered,True,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,72.20,True,14.0,True
3,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,2018-02-13,delivered,True,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,28.62,True,3.0,True
4,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,2017-05-16,delivered,True,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07,75.16,True,10.0,True

In [7]:
fact_orders.isnull().sum()

order_id                            0
customer_id                         0
order_purchase_date                 0
order_status                        0
is_delivered                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
total_payment_value                 0
is_valid_delivery_sequence          0
delivery_days                    4359
is_on_time_delivery              4359
dtype: int64

fact_orders contains missing values in the date columns

#### Fact_Order_Items

In [8]:
print(f"shape of fact_order_items: {fact_order_items.shape}")
print(f"missing values in fact_order_items: {fact_order_items.isnull().sum().sum()}")
print(f"duplicate values in fact_order_items: {fact_order_items.duplicated().sum()}")

fact_order_items.head()

shape of fact_order_items: (112650, 9)
missing values in fact_order_items: 0
duplicate values in fact_order_items: 0

,order_id,order_item_id,product_id,customer_id,order_purchase_date,order_status,price,freight_value,item_total_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,3ce436f183e68e07877b285a838db11a,2017-09-13,delivered,58.90,13.29,72.19
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,f6dd3ec061db4e3987629fe6b26e5cce,2017-04-26,delivered,239.90,19.93,259.83
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,6489ae5e4333f3693df5ad4372dab6d3,2018-01-14,delivered,199.00,17.87,216.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,d4eb9395c8c0431ee92fce09860c5a06,2018-08-08,delivered,12.99,12.79,25.78
4,00048cc3ae777c65dbb7d2a0634bc1ea,1,ef92defde845ab8450f9d70c526ef70f,816cbea969fe5b689b39cfc97a506742,2017-05-15,delivered,21.90,12.69,34.59

#### Fact_Payments

In [9]:
print(f"shape of fact_payments: {fact_payments.shape}")
print(f"missing values in fact_payments: {fact_payments.isnull().sum().sum()}")
print(f"duplicate values in fact_payments: {fact_payments.duplicated().sum()}")

fact_payments.head()

shape of fact_payments: (103886, 8)
missing values in fact_payments: 0
duplicate values in fact_payments: 0

,order_id,payment_sequential,customer_id,order_purchase_date,order_status,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,0a8556ac6be836b46b3e89920d59291c,2018-04-25,delivered,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,f2c7fc58a9de810828715166c672f10a,2018-06-26,delivered,credit_card,1,24.39
2,3d7239c394a212faae122962df514ac7,1,4d7a9b8bba459dce09d1b8fa637a0cba,2017-06-05,delivered,credit_card,3,51.84
3,2480f727e869fdeb397244a21b721b67,1,94967f1e8a9ea8ec6c7129f098f32155,2017-12-13,delivered,credit_card,1,141.90
4,12e5cfe0e4716b59afb0e0f4a3bd6570,1,041cd6848abb3d3ca45e83dc971488fd,2018-03-22,delivered,credit_card,10,157.45